### ISSUE TITLE
Index Creation

### ISSUE THREAD

**Issue by jamesmrollins** [DaanV2/Markdown-Action-Create-Indexes#1]
Hi Daan,
I have a few questions I was hoping you could answer.  For context, I have a repository of training documents containing 12 folders with 2-3 subfolders each.  Within each folder is a markdown file that contains graphics links, text and often a GIF file link.  

- Is your action capable of crawling through these documents to create topic indexes?
- Or is it creating basically a table of contents based on the folder structure?

Thank you in advance for your time.

**Comment by DaanV2** [comment]
Hi James.

It's doing a bit of both. it crawls through all your folder as far down as possible looking for markdown files.

if it found any it will create a list of markdown files and store them under "categories".

if it has created an index page, it will be added to the index of files in the folder above it under the header "Documents".

**Comment by DaanV2** [comment]
I updated the example picture

**Comment by jamesmrollins** [comment]
Thank you for the clarification Daan.  We will check it out.
