### ISSUE TITLE
Customize file extensions to link to (eg. pdf)

### ISSUE THREAD

**Issue by vvasuki** [DaanV2/Markdown-Action-Create-Indexes#13]
Consider https://github.com/vishvAsa/book-pub/tree/master/vishvAsa/kalpa-pattrikAH - I would like for the pdf files there to be automatically linked from the index.md . But it appears that index files generated by this action cannot do so

**Comment by DaanV2** [comment]
hmm, It originally was meant to only link markdown files 🤔 
I could investigate further to allow for the additions of custom files

**Comment by vvasuki** [comment]
Beautiful, thanks!

Could you make the readme better by adding an example like:

```
      - name: Generated Markdown Readmes
        uses: DaanV2/Markdown-Action-Create-Indexes@v5.0.0
        with:
          include: |
                *.pdf
                *.mobi
                *.epub
                *.zip
```


(I was confused by "grep pattern" - I supposed you meant "glob pattern").

Also, for non-md files, can you show the extensions as well, rather than just the basenames (as in https://vishvasa.github.io/book-pub/vishvAsa/kalpa-pattrikAH/upanayanam/ )?

**Comment by vvasuki** [comment]
Also it is strange how some links go to index.md files, rather than the corresponding html ... - https://vishvasa.github.io/book-pub/Rajaraman,%20shngkro%20raajaaraamsuunuH%20Shankar/index.md is what I get when I click  "[Rajaraman, shngkro raajaaraamsuunuH Shankar]" in https://vishvasa.github.io/book-pub/ (Job is here - https://github.com/vishvAsa/book-pub/actions/runs/8306743431/job/22735178327 )
