### ISSUE TITLE
Error: Process completed with exit code 128.

### ISSUE THREAD

**Issue by zer0Kerbal** [DaanV2/Markdown-Action-Create-Indexes#2]
Probably something I did - but maybe you can/will help me track down this issue:

> [master f117a49] auto: Generated markdown indexes
> 2 files changed, 21 insertions(+)
> create mode 100644 docs/LegalMumboJumbo/index.md
> create mode 100644 docs/index.md
> remote: Permission to zer0Kerbal/SphericalTanks.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/zer0Kerbal/SphericalTanks/': The requested URL returned error: 403
> Error: Process completed with exit code [12](https://github.com/zer0Kerbal/SphericalTanks/runs/6399991764?check_suite_focus=true#step:4:12)8.

**Comment by zer0Kerbal** [comment]
![image](https://user-images.githubusercontent.com/39887717/168336295-1d5177f1-c8f6-4174-85fa-2dd7a054bf01.png)

**Comment by DaanV2** [comment]
Sorry I didnt respond earlier, just got the notification!

**Comment by zer0Kerbal** [comment]
> Sorry I didnt respond earlier, just got the notification!

first @DaanV2, thank you for this action!

second, all good. and still thank you for responding. very much appreciated!

zed'K

**Comment by zer0Kerbal** [comment]
hello @DaanV2 - needs another update

> Process completed with exit code 128.

> [build](https://github.com/zer0Kerbal/ScienceInstruments/actions/runs/4633331142/jobs/8198433901)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: DaanV2/Markdown-Action-Create-Indexes@main. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by zer0Kerbal** [comment]
@DaanV2 Thank you.

this should interest you in case you want to get ahead of the curve.
also:
![image](https://user-images.githubusercontent.com/39887717/230666935-1e8398a5-992d-4050-9736-cd7cc01692a2.png)

**Comment by DaanV2** [comment]
I wanted to 🙁 , but the pipeline only accepts node12 or node16.

**Comment by zer0Kerbal** [comment]
Again - thank you.

**Comment by zer0Kerbal** [comment]
@DaanV2 was still getting ec 128 - but from the commit section so added:
```
permissions:
  pull-requests: write
```

might have to use `permissions: write-all` instead
